<?php

namespace ContainerEw7R0Mn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6CS2dNNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6CS2dNN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6CS2dNN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'tokenRepository' => ['privates', 'App\\Repository\\TokenRepository', 'getTokenRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'mailer' => '?',
            'tokenRepository' => 'App\\Repository\\TokenRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
