<?php

namespace ContainerEw7R0Mn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MHPHtrTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MHPHtrT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MHPHtrT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'confirmRepository' => ['privates', 'App\\Repository\\ConfirmRepository', 'getConfirmRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'confirmRepository' => 'App\\Repository\\ConfirmRepository',
            'entityManager' => '?',
            'mailer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
