<?php

namespace ContainerEw7R0Mn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TKm5lL2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TKm5lL2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TKm5lL2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'securityContext' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'authenticationUtils' => '?',
            'securityContext' => '?',
        ]);
    }
}
