<?php

namespace ContainerEw7R0Mn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WX9uosaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wX9uosa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wX9uosa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tokenRepository' => ['privates', 'App\\Repository\\TokenRepository', 'getTokenRepositoryService', true],
        ], [
            'tokenRepository' => 'App\\Repository\\TokenRepository',
        ]);
    }
}
