<?php

namespace ContainerDWJSUTd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gooei0FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gooei0F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gooei0F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'confirmRepository' => ['privates', 'App\\Repository\\ConfirmRepository', 'getConfirmRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'confirmRepository' => 'App\\Repository\\ConfirmRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
