<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBUBi0i6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBUBi0i6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBUBi0i6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBUBi0i6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBUBi0i6\App_KernelDevDebugContainer([
    'container.build_hash' => 'BUBi0i6',
    'container.build_id' => '47909990',
    'container.build_time' => 1699788585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBUBi0i6');
