<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEw7R0Mn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEw7R0Mn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEw7R0Mn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEw7R0Mn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEw7R0Mn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ew7R0Mn',
    'container.build_id' => '9b6c7c72',
    'container.build_time' => 1722757539,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEw7R0Mn');
