<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::dashboard'], [], [['text', '/dashboard']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_post' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/post']], [], [], []],
    'posts.pdo' => [[], ['_controller' => 'App\\Controller\\PostController::pdo'], [], [['text', '/pdo']], [], [], []],
    'app_mail' => [[], ['_controller' => 'App\\Controller\\PostController::mail'], [], [['text', '/mail']], [], [], []],
    'confirmTest' => [[], ['_controller' => 'App\\Controller\\PostController::confirmTest'], [], [['text', '/confirmTest']], [], [], []],
    'post.confirm' => [[], ['_controller' => 'App\\Controller\\PostController::confirm'], [], [['text', '/confirm']], [], [], []],
    'post.checkConfirm' => [[], ['_controller' => 'App\\Controller\\PostController::checkConfirm'], [], [['text', '/checkConfirm']], [], [], []],
    'app_recover' => [[], ['_controller' => 'App\\Controller\\RecoverController::recover'], [], [['text', '/recover']], [], [], []],
    'app_sendToken' => [[], ['_controller' => 'App\\Controller\\RecoverController::sendToken'], [], [['text', '/sendToken']], [], [], []],
    'app_reset' => [['token'], ['_controller' => 'App\\Controller\\RecoverController::resetPassword'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/reset']], [], [], []],
    'app_reset_password' => [[], ['_controller' => 'App\\Controller\\RecoverController::resetPasswordConfirm'], [], [['text', '/reset-password']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
];
