<?php

namespace Container0xS1mn4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecoverControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RecoverController' shared autowired service.
     *
     * @return \App\Controller\RecoverController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RecoverController.php';

        $container->services['App\\Controller\\RecoverController'] = $instance = new \App\Controller\RecoverController(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\RecoverController', $container));

        return $instance;
    }
}
